spring.application.name=api

game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

game.taquin.default-player-count=1
game.taquin.default-board-size=4

game.connectfour.default-player-count=2
game.connectfour.default-board-size=7

spring.profiles.active=mysql

server.address=0.0.0.0
users.api.url=http://localhost:8081

### À mettre dans un fichier application-local.properties###
jwt.secret=ta-cle-secrete-tres-longue-et-difficile-a-deviner